include:
  - board: seeeduino_xiao_ble
    shield: zonkeytest_L rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: zonkeytest_R rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
